#PBS -q class
#PBS -l nodes=jinx8
#PBS -l walltime=00:04:00
#PBS -N numa

# Changes to the directory we were in when we
# submit the job:

cd $PBS_O_WORKDIR

# Runs a bunch of standard command-line
# utilities, just as an example:

echo "Script began:" `date`
echo "Node:" `hostname`
echo "Current directory: ${PWD}"

/nethome/rvuduc3/local/jinx/likwid/2.2.1-ICC/bin/likwid-topology -g

echo ""
echo "=== Done! ==="

# eof
